version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-taskmanager
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: taskmanager
    ports:
      - "5432:5432"
    volumes:
      - postgres-taskmanager-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-taskmanager
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]

volumes:
  postgres-taskmanager-data:
